pod 'AFNetworking', '~> 3.1.0'       # 网络请求

pod 'ASIHTTPRequest', '~> 1.8.2'

pod 'EGOCache', '~> 2.1.3'          #缓存

pod 'FMDB', '~> 2.6.2'                 #数据库

pod 'AwesomeMenu', '~> 1.0.0'       #path效果

pod 'MJRefresh', '~> 3.1.0'          #加载刷新

pod 'KYJellyPullToRefresh', '~> 1.1.0'

pod 'LCProgressHUD', '~> 1.0.6'    #菊花

pod 'Masonry', '~> 1.0.0'              #代码约束

pod 'MJExtension', '~> 3.0.10'     #数据模型

pod 'SBJson', '~> 4.0.2'

pod 'YYModel', '~> 1.0.3'

pod 'SDWebImage', '~> 3.7.5'        #图片异步

pod 'YYCache', '~> 1.0.3'

pod 'YYAsyncLayer', '~> 1.0'

pod 'YYCategories', '~> 1.0.2'

pod 'YYText', '~> 1.0.5'

pod 'YYKeyboardManager', '~> 1.0.1'

pod 'YYWaterflowLayout', '~> 1.0.0'

pod 'YYWebImage', '~> 1.0.3'

pod 'JPush', '~> 2.1.6'  #极光推送


# 主模块(必须)
pod 'ShareSDK3', '~> 3.2.5'
# Mob 公共库(必须) 如果同时集成SMSSDK iOS2.0:可看此注意事项：http://bbs.mob.com/thread-20051-1-1.html
pod 'MOBFoundation'

# UI模块(非必须，需要用到ShareSDK提供的分享菜单栏和分享编辑页面需要以下1行)
pod 'ShareSDK3/ShareSDKUI'

# 平台SDK模块(对照一下平台，需要的加上。如果只需要QQ、微信、新浪微博，只需要以下3行)
pod 'ShareSDK3/ShareSDKPlatforms/QQ'

pod 'ShareSDK3/ShareSDKPlatforms/SinaWeibo'

pod 'ShareSDK3/ShareSDKPlatforms/WeChat'


